/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.ratelimiter.model.Tier;
import org.example.ratelimiter.model.User;
import org.example.ratelimiter.service.RateLimiterService;

public class App {

}
